name: Sync to GitHub Pages Repo
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to Website Repo
        env:
          PAT: ${{ secrets.SYNC_PAT }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # We add a new remote named 'target'
          git remote add target https://x-access-token:${PAT}@github.com/sunnykalola73/sunnykalola73.github.io.git
          
          # Push the main branch to the target remote
          git push target main --force
