name: Sync to GitHub Pages Repo
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # This prevents the default token from interfering with your PAT
          persist-credentials: false 

      - name: Push to Website Repo
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Force push to the destination repo using your SYNC_PAT
          git push --force https://x-access-token:${{ secrets.SYNC_PAT }}@://github.com main
