name: Sync to GitHub Pages Repo
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to Website Repo
        env:
          PAT: ${{ secrets.SYNC_PAT }}
        run: |
          echo "Secret length is ${#PAT}"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # This version uses an environment variable for cleaner URL construction
          git push --force "https://x-access-token:$PAT@://github.com" main
